apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-ci
  namespace: hextris
secrets:
- name: jenkins-ci-token
---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-ci-token
  namespace: hextris
  annotations:
    kubernetes.io/service-account.name: jenkins-ci
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-ci-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: jenkins-ci
  namespace: hextris