apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.agent.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.agent.name }}
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest
    args: ['\$(JENKINS_SECRET)', '\$(JENKINS_NAME)']
    resources:
      requests:
        memory: {{ .Values.resources.jnlp.requests.memory }}
        cpu: {{ .Values.resources.jnlp.requests.cpu }}
      limits:
        memory: {{ .Values.resources.jnlp.limits.memory }}
        cpu: {{ .Values.resources.jnlp.limits.cpu }}
  
  - name: docker
    image: docker:latest
    command: ['sleep']
    args: ['infinity']
    env:
    - name: DOCKER_HOST
      value: tcp://docker:2376
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock
    resources:
      requests:
        memory: {{ .Values.resources.docker.requests.memory }}
        cpu: {{ .Values.resources.docker.requests.cpu }}
      limits:
        memory: {{ .Values.resources.docker.limits.memory }}
        cpu: {{ .Values.resources.docker.limits.cpu }}
  
  - name: kubectl
    image: bitnami/kubectl:latest
    command: ['sleep']
    args: ['infinity']
    resources:
      requests:
        memory: {{ .Values.resources.kubectl.requests.memory }}
        cpu: {{ .Values.resources.kubectl.requests.cpu }}
      limits:
        memory: {{ .Values.resources.kubectl.limits.memory }}
        cpu: {{ .Values.resources.kubectl.limits.cpu }}

  volumes:
  - name: docker-sock
    hostPath:
      path: {{ .Values.volumes.dockerSockPath }}